#!/bin/bash

# Get all the files that are staged
fileArray=($(git diff --name-only --cached | grep -E "\.kt$"))

# Ignore removed files
for file in "${fileArray[@]}"; do
  if [ ! -f "$file" ]; then
    fileArray=("${fileArray[@]/$file}")
  fi
done

# If no kt files are staged, then exit
if [ ${#fileArray[@]} -eq 0 ]; then
  echo "No kt files to check"
  exit 0
fi

# Get the input files for detekt ignoring removed files
detektInput=$(echo "${fileArray[@]}" | tr ' ' '\n' | grep -vE "^\s*$" | tr '\n' ',' | sed 's/,$//')

OUTPUT=$(detekt -c detekt.yml --input "$detektInput" --plugins lint/detekt-compose-0.4.5-all.jar 2>&1)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo $OUTPUT
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
else
    echo $OUTPUT
    echo "***********************************************"
    echo "                 detekt passed                 "
    echo "***********************************************"
fi
