# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  detekt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get dependencies
        run: sudo apt-get install -y curl unzip
      - name: Fetch detekt jar
        run: curl -sSLO https://github.com/detekt/detekt/releases/download/v1.23.3/detekt-cli-1.23.3.zip
      - name: Unzip detekt
        run: unzip detekt-cli-1.23.3.zip
      - name: Run detekt 
        run: ./detekt-cli-1.23.3/bin/detekt-cli --report html:reports/detekt.html -c ./detekt.yml
